/*
 * pcjr_bridge.ino
 * ---------------
 * Unified Arduino sketch that can be switched between two modes:
 *   '0' → 433 MHz outlet control (uses outlet_control.h)
 *   '1' → PCjr IR keyboard bridge (uses Timer3 on pin 5)
 *
 * Mode selection happens after a hardware reset (DTR pulse).  No in‑band
 * switching — the two modes never interfere.
 */

#include "outlet_control.h"   // 433 MHz TX

// ---------- Compile‑time flag for _delay_us(float) ----------
#define __DELAY_ROUND_CLOSEST__
#include <util/delay.h>

// ---------- IR hardware constants (verbatim from original) ----------
const int irPin = 5;           // PE3 on ATmega2560

#define BURST_DURATION     62.5
#define LOGIC_1_SILENCE   377.5
#define LOGIC_0_SILENCE_1 220.0
#define LOGIC_0_SILENCE_2 157.5
#define START_BIT_SILENCE 310
#define INTER_BYTE_GAP    4840

// 40 kHz carrier generated by Timer3 in CTC mode
#define TIMER3_TOP  24        // 16 MHz / (2 * 40 kHz) / 8 - 1

// ---------- Inline carrier helpers ----------
inline void carrierOn() {
  TCCR3A |= (1 << COM3A0);    // toggle pin 5 on each match
  TCCR3B |= (1 << CS31);      // start clock (prescaler /8)
}

inline void carrierOff() {
  TCCR3B &= ~(1 << CS31);     // stop clock
  TCCR3A &= ~(1 << COM3A0);   // disconnect timer from pin
  TCNT3 = 0;                  // reset counter
  PORTE |= (1 << 3);          // force pin HIGH (LED off, active‑low)
}

// ---------- Manchester encoding primitives (unchanged) ----------
inline void sendOne() {
  carrierOn();   _delay_us(BURST_DURATION);
  carrierOff();  _delay_us(LOGIC_1_SILENCE);
}

inline void sendZero() {
  carrierOff();  _delay_us(LOGIC_0_SILENCE_1);
  carrierOn();   _delay_us(BURST_DURATION);
  carrierOff();  _delay_us(LOGIC_0_SILENCE_2);
}

inline void sendStart() {
  carrierOn();   _delay_us(BURST_DURATION);
  carrierOff();  _delay_us(START_BIT_SILENCE);
}

// ---------- Transmit a single scan code byte with odd parity ----------
void sendByte(uint8_t data) {
  noInterrupts();               // timing‑critical

  sendStart();

  uint8_t parity = 0;
  for (uint8_t i = 0; i < 8; ++i) {
    if (data & 1) {
      sendOne();
      ++parity;
    } else {
      sendZero();
    }
    data >>= 1;
  }

  // Odd parity: if number of ones is odd, send 0; else send 1
  if (parity & 1) sendZero();
  else            sendOne();

  interrupts();

  _delay_us(INTER_BYTE_GAP);
}

// ---------- Global state ----------
enum Mode { MODE_WAIT, MODE_RF, MODE_IR };
Mode currentMode = MODE_WAIT;

// ---------- Soft‑reset helper ----------
void(* resetFunc)(void) = 0;

// ---------- Initialisation ----------
void setup() {
  Serial.begin(600);

  // --- IR hardware init (safe for both modes) ---
  pinMode(irPin, OUTPUT);
  PORTE |= (1 << 3);             // force IR LED off
  TCCR3A = 0;
  TCCR3B = 0;
  TCNT3  = 0;
  OCR3A  = TIMER3_TOP;
  TCCR3B = (1 << WGM32);        // CTC mode, clock stopped

  // --- RF module not initialised yet (only when mode 0 is chosen) ---

  // --- Flush stale serial bytes ---
  while (Serial.available()) Serial.read();

  // --- Handshake: wait for a valid mode byte ---
  Serial.println("BOOT");
  while (currentMode == MODE_WAIT) {
    if (Serial.available()) {
      char c = Serial.read();
      if (c == '0') {
        currentMode = MODE_RF;
        setupOutlets();            // init 433 MHz TX
        Serial.println("MODE:RF");
      } else if (c == '1') {
        currentMode = MODE_IR;
        Serial.println("MODE:IR");
      }
      // All other bytes are silently ignored; loop continues waiting
    }
  }
}

// ---------- Main dispatch ----------
void loop() {
  if (currentMode == MODE_RF)       loopRF();
  else if (currentMode == MODE_IR)  loopIR();
}

// ---------- RF outlet control loop ----------
void loopRF() {
  // Wait for two integers: <outlet id> <state> (e.g. "2 1\n")
  while (!Serial.available()) { /* wait */ }
  int id = Serial.parseInt();
  while (!Serial.available()) { /* wait */ }
  int state = Serial.parseInt();

  // Discard any trailing whitespace / newline
  while (Serial.available()) Serial.read();

  // Send the RF command
  sendOutletCommand(id, state);

  // Give the transmitter time to finish, then reboot back to mode‑select
  delay(100);
  resetFunc();
}

// ---------- IR keyboard bridge loop (unchanged) ----------
void loopIR() {
  while (Serial.available()) {
    sendByte(Serial.read());
  }
}